puts "The students at my cohort of Makers Academy are..."
puts "-------------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex De Large"
puts "The Alien"
puts "Terminator"
puts "Freddie Kruger"
puts "The Joker"

print "Overall, we have "
print 9
puts " great students."